# In this notebook we are going to cover some of the most fundamental concepts of tensors using TensorFlow
More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating Tensors
* Tensors & Numpy
* Usint @tf.function ( a wayt to speed up your regular Python fucntions)
* Using GPU's with Tensorflow (CUDA)
* Exercies

## Introduction to Tensors

In [1]:
import tensorflow as tf

print(tf.__version__)

ModuleNotFoundError: No module named 'tensorflow'

## Create tensors with tf.constant()

In [3]:
scalar = tf.constant(7)
scalar

2021-12-10 22:03:10.659342: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimension of a tensor (ndim stands for number of dimension)
scalar.ndim

0

In [5]:
# Create of vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Create a matrix (has more then one dimension)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], [7., 10.], [8., 9.]],
                             dtype=tf.float16)  # you can specify type with dtype maybe you can save some space
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [8]:
# How to increase number of dimensions.
tensor_with_three_dimensions = tf.constant([[[10., 7.], [7., 10.], [8., 9.]]], dtype=tf.float16)
tensor_with_three_dimensions.ndim, tensor_with_three_dimensions

(3,
 <tf.Tensor: shape=(1, 3, 2), dtype=float16, numpy=
 array([[[10.,  7.],
         [ 7., 10.],
         [ 8.,  9.]]], dtype=float16)>)

### Creating tensors with `tf.Variable`

In [9]:
# Create the same tensor with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])
changeable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [10]:
# Trying to change one something
# changeable_tensor[0] = 7

In [11]:
# Use method for inplace operation
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [12]:
# Try change unchangable (probably immutable)
# unchangable_tensor[0].assign(7)

## Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers.

In [13]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)  # set
random_1 = random_1.normal(shape=(3, 2, 1))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2, 1))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
 array([[[-0.7565803 ],
         [-0.06854702]],
 
        [[ 0.07595026],
         [-1.2573844 ]],
 
        [[-0.23193763],
         [-1.8107855 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
 array([[[-0.7565803 ],
         [-0.06854702]],
 
        [[ 0.07595026],
         [-1.2573844 ]],
 
        [[-0.23193763],
         [-1.8107855 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 1), dtype=bool, numpy=
 array([[[ True],
         [ True]],
 
        [[ True],
         [ True]],
 
        [[ True],
         [ True]]])>)

In [14]:
tf.random.uniform(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.56059825, 0.5897697 , 0.01967835],
       [0.5262649 , 0.9717535 , 0.85148454],
       [0.8964828 , 0.39515018, 0.90234697]], dtype=float32)>

### Shuffle the order of elements in tensor

In [15]:
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])
not_shuffled.ndim

2

In [16]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [17]:
exercise_tensor1 = tf.constant([[[10, 7], [3, 4], [2, 5]], [[10, 7], [3, 4], [2, 5]]])
exercise_tensor2 = tf.constant([56])
exercise_tensor3 = tf.constant([[[[17, 7], [3, 231], [22, 5]], [[410, 7], [3, 42], [12, 5]]],
                                [[[103, 7], [341, 4], [244, 55]], [[10, 743], [3, 4], [22222, 5]]]])
exercise_tensor4 = tf.constant([[10, 7], [3, 4], [2, 5]])
exercise_tensor5 = tf.constant(43)

exercise_tensor1, exercise_tensor2, exercise_tensor3, exercise_tensor4, exercise_tensor5

(<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
 array([[[10,  7],
         [ 3,  4],
         [ 2,  5]],
 
        [[10,  7],
         [ 3,  4],
         [ 2,  5]]], dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([56], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
 array([[[[   17,     7],
          [    3,   231],
          [   22,     5]],
 
         [[  410,     7],
          [    3,    42],
          [   12,     5]]],
 
 
        [[[  103,     7],
          [  341,     4],
          [  244,    55]],
 
         [[   10,   743],
          [    3,     4],
          [22222,     5]]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=43>)

In [18]:
tf.random.shuffle(exercise_tensor3, seed=23)

<tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
array([[[[   17,     7],
         [    3,   231],
         [   22,     5]],

        [[  410,     7],
         [    3,    42],
         [   12,     5]]],


       [[[  103,     7],
         [  341,     4],
         [  244,    55]],

        [[   10,   743],
         [    3,     4],
         [22222,     5]]]], dtype=int32)>

In [19]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
# Create a tensor of all zeroes
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors


In [21]:
# You can also turn NumPy arrays into tensors
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A
# Capital letters are used for matrices or tensors but non-capital for vectors for example
# X = tf.constant([[3,4],[3,4]])
# y = tf.constant([3,4,5,6])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A, shape=(8, 3))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors
When dealing with tenosrs you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [23]:
# Create rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor.ndim, rank_4_tensor.shape, tf.size(rank_4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [24]:
# Getting tensor by index
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
# Get various attributes of tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimension (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements: ", tf.size(rank_4_tensor))

Datatype of every element:  <dtype: 'float32'>
Number of dimension (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements:  tf.Tensor(120, shape=(), dtype=int32)


### Indexing tensors
Tensors can be indexed just like Python lists

In [26]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# Get the first elemenet from each dimension from each index except the final one
rank_4_tensor[:1, :1, :1, :5]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# Adding extra dimension to tensor
rank_2_tensor = tf.constant([[10, 7], [10, 7]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [29]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7], dtype=int32)>

In [30]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
# rank_3_tensor = rank_2_tensor[:,:, tf.newaxis] # You can also do it like this but it's more clicking :/
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[10],
        [ 7]]], dtype=int32)>

In [31]:
# Alternative way to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[10],
        [ 7]]], dtype=int32)>

Manipulatin tensors (tensors operations)
**Basic operations**

In [32]:
# Addition
tensor = tf.constant([[10, 7], [3, 4]])
tensor += 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [33]:
# Multiplication
tensor * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[60, 51],
       [39, 42]], dtype=int32)>

In [34]:
# Subtraction
tensor - 15

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]], dtype=int32)>

In [35]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

### Matrix Multiplication
It's most important operation!!! You can't work without it

In [36]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [37]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

### Aggregation Tesnors
Aggregating tensors = condensing them from multiple values to a smaller amount of values.

In [38]:
# Getting the absolute values
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Aggregation functions:
* Minimum
* Maximum
* Mean
* Sum

In [39]:
B = tf.constant([[5, 6, 7], [2, 3, 5], [1, -23, 1465]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[   5,    6,    7],
       [   2,    3,    5],
       [   1,  -23, 1465]], dtype=int32)>

In [40]:
# Getting Minimum
# Interseting difference between minimum and reduce_min

Y = tf.constant([[-5, 22, 7], [111, -3, 5], [1, -23, 1465]])
tf.reduce_min(B), tf.minimum(B, Y)

(<tf.Tensor: shape=(), dtype=int32, numpy=-23>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[  -5,    6,    7],
        [   2,   -3,    5],
        [   1,  -23, 1465]], dtype=int32)>)

In [41]:
# Getting Maximum
# Same as aboce
tf.reduce_max(B), tf.maximum(B, Y)

(<tf.Tensor: shape=(), dtype=int32, numpy=1465>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[   5,   22,    7],
        [ 111,    3,    5],
        [   1,  -23, 1465]], dtype=int32)>)

In [42]:
# Getting Mean
tf.reduce_mean(B)

<tf.Tensor: shape=(), dtype=int32, numpy=163>

In [43]:
# Getting Sum
tf.reduce_sum(B)

<tf.Tensor: shape=(), dtype=int32, numpy=1471>

## FInd the positional maximum and minimum

In [44]:
# Create a new tensor for fiding minimum and maximum positional
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.17384171, 0.3562621 , 0.36891103, 0.3535546 , 0.51270306,
       0.8830923 , 0.20754564, 0.79918325, 0.6942719 , 0.6215781 ,
       0.9336704 , 0.52336895, 0.6751329 , 0.5606936 , 0.680267  ,
       0.52606964, 0.6118132 , 0.30906236, 0.28911722, 0.10508788,
       0.91737676, 0.9341794 , 0.6332122 , 0.16160667, 0.79238605,
       0.6331922 , 0.10267389, 0.40438592, 0.07559252, 0.09468174,
       0.86752295, 0.7490368 , 0.7862686 , 0.4197024 , 0.60167885,
       0.8590131 , 0.22180104, 0.27181697, 0.39315343, 0.54017997,
       0.7773317 , 0.38223374, 0.7484461 , 0.6009741 , 0.02105439,
       0.48964012, 0.56929374, 0.5908209 , 0.07676697, 0.9087043 ],
      dtype=float32)>

In [45]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=21>

In [46]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9341794>

In [47]:
# Findd the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9341794>

In [48]:
# Index on our largest value position
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [49]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.021054387>

### Squeezing a tensor (removing all single dimension)

In [50]:
# Create a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.87055516, 0.19106126, 0.19867516, 0.9717665 , 0.5363275 ,
           0.9193497 , 0.46838903, 0.65209377, 0.7730299 , 0.30466795,
           0.99726653, 0.11224985, 0.06992686, 0.61587036, 0.23611414,
           0.43424904, 0.9349748 , 0.16771412, 0.6927868 , 0.4657315 ,
           0.48522937, 0.51071715, 0.4817487 , 0.17827117, 0.26881754,
           0.02212024, 0.5309231 , 0.32153845, 0.03932822, 0.66922045,
           0.04482877, 0.00555539, 0.5120002 , 0.81830084, 0.04063106,
           0.96259856, 0.9479773 , 0.0381639 , 0.19600463, 0.38536513,
           0.50108147, 0.31394267, 0.43843436, 0.93790174, 0.80534744,
           0.19445097, 0.9112693 , 0.21125543, 0.27112103, 0.62632203]]]]],
      dtype=float32)>

In [51]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [52]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.87055516, 0.19106126, 0.19867516, 0.9717665 , 0.5363275 ,
       0.9193497 , 0.46838903, 0.65209377, 0.7730299 , 0.30466795,
       0.99726653, 0.11224985, 0.06992686, 0.61587036, 0.23611414,
       0.43424904, 0.9349748 , 0.16771412, 0.6927868 , 0.4657315 ,
       0.48522937, 0.51071715, 0.4817487 , 0.17827117, 0.26881754,
       0.02212024, 0.5309231 , 0.32153845, 0.03932822, 0.66922045,
       0.04482877, 0.00555539, 0.5120002 , 0.81830084, 0.04063106,
       0.96259856, 0.9479773 , 0.0381639 , 0.19600463, 0.38536513,
       0.50108147, 0.31394267, 0.43843436, 0.93790174, 0.80534744,
       0.19445097, 0.9112693 , 0.21125543, 0.27112103, 0.62632203],
      dtype=float32)>

In [53]:
# Create a list of indicies
some_list = [0, 1, 2, 3]  # could be red green, blue, purple

# One hot encode our list of indicies
tf.one_hot(some_list, 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [54]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="Yo i love you", off_value="Fuck me")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yo i love you', b'Fuck me', b'Fuck me', b'Fuck me'],
       [b'Fuck me', b'Yo i love you', b'Fuck me', b'Fuck me'],
       [b'Fuck me', b'Fuck me', b'Yo i love you', b'Fuck me'],
       [b'Fuck me', b'Fuck me', b'Fuck me', b'Yo i love you']],
      dtype=object)>

### Squaring, log, square root

In [55]:
# Create new tensor
H = tf.constant(tf.random.normal([4, 3, 5]))
Vector_H = tf.range(1, 10)
Vector_H, H

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(4, 3, 5), dtype=float32, numpy=
 array([[[ 0.1991261 ,  0.4447361 , -0.4685533 ,  0.29277787,
          -1.1352966 ],
         [-0.13092624,  0.22018951,  1.0324655 ,  0.47785997,
          -0.7187718 ],
         [-0.4567562 ,  0.01265275,  0.50958693,  0.38857892,
           0.31420812]],
 
        [[ 0.35930106, -0.05221606,  1.684033  ,  0.3160261 ,
          -1.2318717 ],
         [-0.5755285 ,  0.8478414 ,  0.42361942,  2.5533686 ,
           1.0884615 ],
         [-0.4980333 , -0.6823565 , -1.0755985 ,  0.94167954,
          -1.5900137 ]],
 
        [[ 0.5884598 ,  1.1577642 , -0.8172691 , -1.3185694 ,
          -0.7947699 ],
         [ 1.1550051 ,  1.318201  ,  0.5044818 , -0.10229621,
          -1.6925608 ],
         [-0.29983944, -2.1859126 ,  1.28438   , -1.6091925 ,
           0.02824457]],
 
        [[-1.1715858 ,  0.13306406, -0.44051743, -0.6749718 ,
         

In [56]:
# Square
tf.square(Vector_H), tf.square(H)

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(4, 3, 5), dtype=float32, numpy=
 array([[[3.9651200e-02, 1.9779019e-01, 2.1954221e-01, 8.5718878e-02,
          1.2888983e+00],
         [1.7141679e-02, 4.8483420e-02, 1.0659850e+00, 2.2835015e-01,
          5.1663291e-01],
         [2.0862623e-01, 1.6009207e-04, 2.5967884e-01, 1.5099359e-01,
          9.8726742e-02]],
 
        [[1.2909725e-01, 2.7265169e-03, 2.8359673e+00, 9.9872492e-02,
          1.5175079e+00],
         [3.3123305e-01, 7.1883500e-01, 1.7945342e-01, 6.5196910e+00,
          1.1847485e+00],
         [2.4803716e-01, 4.6561036e-01, 1.1569121e+00, 8.8676035e-01,
          2.5281436e+00]],
 
        [[3.4628493e-01, 1.3404180e+00, 6.6792876e-01, 1.7386253e+00,
          6.3165915e-01],
         [1.3340368e+00, 1.7376537e+00, 2.5450188e-01, 1.0464515e-02,
          2.8647621e+00],
         [8.9903690e-02, 4.7782140e+00, 1.6496319e+00, 2.5895004e+00,
 

In [57]:
#Square root
tf.sqrt(tf.cast(Vector_H, dtype=tf.float32)), tf.sqrt(tf.cast(H, dtype=tf.float32))

(<tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
        2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>,
 <tf.Tensor: shape=(4, 3, 5), dtype=float32, numpy=
 array([[[0.44623548, 0.6668853 ,        nan, 0.5410895 ,        nan],
         [       nan, 0.46924356, 1.016103  , 0.6912742 ,        nan],
         [       nan, 0.11248444, 0.7138536 , 0.623361  , 0.56054264]],
 
        [[0.59941727,        nan, 1.2977029 , 0.562162  ,        nan],
         [       nan, 0.920783  , 0.65086055, 1.5979263 , 1.0432936 ],
         [       nan,        nan,        nan, 0.9704017 ,        nan]],
 
        [[0.7671113 , 1.0759945 ,        nan,        nan,        nan],
         [1.0747117 , 1.1481293 , 0.7102688 ,        nan,        nan],
         [       nan,        nan, 1.133305  ,        nan, 0.16806121]],
 
        [[       nan, 0.3647794 ,        nan,        nan,        nan],
         [0.9727525 , 0.4255771 , 1.0431

In [58]:
# Log
tf.math.log(tf.cast(Vector_H, dtype=tf.float32)), tf.math.log(tf.cast(H, dtype=tf.float32))

(<tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246], dtype=float32)>,
 <tf.Tensor: shape=(4, 3, 5), dtype=float32, numpy=
 array([[[-1.613817  , -0.81027424,         nan, -1.2283411 ,
                  nan],
         [        nan, -1.5132667 ,  0.03194959, -0.73843753,
                  nan],
         [        nan, -4.3698807 , -0.6741548 , -0.945259  ,
          -1.1576997 ]],
 
        [[-1.0235946 ,         nan,  0.52119154, -1.1519306 ,
                  nan],
         [        nan, -0.16506171, -0.85891986,  0.9374135 ,
           0.08476525],
         [        nan,         nan,         nan, -0.06009025,
                  nan]],
 
        [[-0.5302467 ,  0.14649072,         nan,         nan,
                  nan],
         [ 0.14410476,  0.2762679 , -0.68422353,         nan,
                  nan],
         [        nan,         nan,  0.2502761 ,         nan,
          -3

### Numpy and Tensors Fino alla fine
TensorFlow interacts with Numpy arrays

In [59]:
J = tf.constant(np.array([3., 6., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  6., 10.])>

In [60]:
# Convert back to numpy
np.array(J)

array([ 3.,  6., 10.])

In [61]:
#C Convert tensor J to a numpy array
J.numpy()

array([ 3.,  6., 10.])

In [62]:
J = tf.constant([3.])
J.numpy()[0]

3.0

### Finding access to GPU's

In [63]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

🛠 **Exercises**

In [64]:
vector = tf.constant(1)
scalar = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2], [1, 2]])
tensor = tf.constant([[[1, 2], [1, 2]], [[1, 2], [1, 2]]])

In [65]:
print(vector.shape, vector.ndim, tf.size(vector))
print(scalar.shape, scalar.ndim, tf.size(scalar))
print(matrix.shape, matrix.ndim, tf.size(matrix))
print(tensor.shape, tensor.ndim, tf.size(tensor))

() 0 tf.Tensor(1, shape=(), dtype=int32)
(3,) 1 tf.Tensor(3, shape=(), dtype=int32)
(2, 2) 2 tf.Tensor(4, shape=(), dtype=int32)
(2, 2, 2) 3 tf.Tensor(8, shape=(), dtype=int32)


In [66]:
random_tensor = tf.constant(tf.random.uniform([5, 300]))
random_tensor2 = tf.constant(tf.random.uniform([5, 300]))
random_tensor

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.82098544, 0.7968776 , 0.7071496 , ..., 0.00541282, 0.43010163,
        0.32153213],
       [0.81933475, 0.3232597 , 0.20055556, ..., 0.37163985, 0.4365586 ,
        0.7327119 ],
       [0.09212732, 0.50701964, 0.43402743, ..., 0.12545002, 0.6689173 ,
        0.31201065],
       [0.53973055, 0.27318156, 0.8144944 , ..., 0.90646744, 0.39042544,
        0.86241746],
       [0.8081169 , 0.8849478 , 0.8561077 , ..., 0.17711103, 0.12958229,
        0.17731011]], dtype=float32)>

In [67]:
random_tensor * random_tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.1923481 , 0.6957676 , 0.56010324, ..., 0.00435082, 0.34822926,
        0.1658657 ],
       [0.04069028, 0.09363652, 0.08016621, ..., 0.36092225, 0.2823824 ,
        0.31196302],
       [0.02162179, 0.23998562, 0.28040403, ..., 0.01781894, 0.31303516,
        0.1688228 ],
       [0.04281179, 0.2353057 , 0.6887474 , ..., 0.60766184, 0.28857028,
        0.394319  ],
       [0.01777208, 0.23049541, 0.695054  , ..., 0.16338414, 0.01488276,
        0.15114649]], dtype=float32)>

In [68]:
tf.tensordot(random_tensor, tf.transpose(random_tensor2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.81877 , 73.3745  , 67.44275 , 73.3294  , 69.19296 ],
       [75.999344, 78.67389 , 74.936035, 76.682976, 78.67911 ],
       [69.61885 , 72.63016 , 69.35687 , 72.051926, 75.19914 ],
       [75.91149 , 79.109146, 77.69722 , 78.08791 , 79.17201 ],
       [73.360985, 77.52809 , 73.744385, 75.32469 , 77.36296 ]],
      dtype=float32)>

In [69]:
three_dimension_tensor = tf.constant(tf.random.uniform([224, 224, 3]))
three_dimension_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.03921247, 0.85313535, 0.28924525],
        [0.745862  , 0.2791189 , 0.49690723],
        [0.7002903 , 0.3131559 , 0.86659837],
        ...,
        [0.5769839 , 0.13742232, 0.6695508 ],
        [0.15684664, 0.76218784, 0.8869479 ],
        [0.3030064 , 0.43199778, 0.47473896]],

       [[0.81893814, 0.00339067, 0.10909343],
        [0.00639129, 0.49482727, 0.819842  ],
        [0.53222847, 0.38277602, 0.11143792],
        ...,
        [0.46081722, 0.8566439 , 0.93232787],
        [0.72393715, 0.33472955, 0.9021816 ],
        [0.41843152, 0.6286589 , 0.6304827 ]],

       [[0.02029335, 0.08946967, 0.08241725],
        [0.17040968, 0.25607836, 0.2872864 ],
        [0.88510704, 0.99014723, 0.35424864],
        ...,
        [0.16597152, 0.75637937, 0.8941238 ],
        [0.3858788 , 0.15954375, 0.02287829],
        [0.51850414, 0.7411343 , 0.5773784 ]],

       ...,

       [[0.78580344, 0.5485771 , 0.8250936 ],
        [0.07

In [70]:
tf.reduce_min(three_dimension_tensor), tf.reduce_max(three_dimension_tensor)

(<tf.Tensor: shape=(), dtype=float32, numpy=2.0861626e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99999213>)

In [71]:
too_big_tensor = tf.constant(tf.random.uniform([1, 224, 224, 3]))
too_big_tensor.shape, tf.squeeze(too_big_tensor)

(TensorShape([1, 224, 224, 3]),
 <tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.17317307, 0.54796815, 0.8337476 ],
         [0.92669106, 0.14969587, 0.654405  ],
         [0.11483848, 0.14294052, 0.9729705 ],
         ...,
         [0.78095233, 0.51147056, 0.16409326],
         [0.8825005 , 0.02101684, 0.10928738],
         [0.3070798 , 0.9143323 , 0.5337107 ]],
 
        [[0.31729305, 0.3177253 , 0.47903478],
         [0.04440892, 0.14844513, 0.07437825],
         [0.23166132, 0.02139962, 0.82001686],
         ...,
         [0.7814666 , 0.7256013 , 0.85461855],
         [0.03053319, 0.3686459 , 0.06910467],
         [0.05689526, 0.15240586, 0.92215204]],
 
        [[0.5314971 , 0.7505393 , 0.6533654 ],
         [0.44043362, 0.6114626 , 0.19690108],
         [0.66893137, 0.6294842 , 0.24339366],
         ...,
         [0.50917244, 0.13840985, 0.12988377],
         [0.78989685, 0.14676154, 0.1642201 ],
         [0.23577046, 0.7036513 , 0.9572538 ]],
 
        ...,
 


In [72]:
small_tensor = tf.range(0, 10)
small_tensor, tf.argmax(small_tensor)

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=9>)

In [73]:
tf.one_hot(small_tensor, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>